#!/bin/sh

# Function
function take () {
    mkdir -p $1
    cd $1
}

function gpg-export () {
    gpg --armor --export $1
}

function randomchars() {
    openssl rand -base64 $1
}

function prkill() {
    kill $(ps aux | grep $1 | awk '{print $2; exit}')
}

# Function to source files if they exist
function zsh_add_file() {
    if [ -f "$ZDOTDIR/$1" ]; then
        source "$ZDOTDIR/$1"
    fi
}

function add_all_ssh() {
  eval `ssh-agent` &>/dev/null

  if [ ! -d "${HOME}/.ssh" ]; then
    echo "No .ssh directory found"
    return
  fi


  for key in "${HOME}/.ssh"/*; do
    ext="${key##*.}"
    if [ "$ext" = "pub" ] ||
    [ "$key" = "${HOME}/.ssh/known_hosts" ]  ||
    [ "$key" = "${HOME}/.ssh/known_hosts.old" ] ||
    [ "$key" = "${HOME}/.ssh/authorized_keys" ]; then
      continue
    fi
    ssh-add "$key"
  done
}

function zsh_add_plugin() {
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ]; then 
        # For plugins
        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh" || \
        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.zsh"
    else
        git clone "git@github.com:$1.git" "$ZDOTDIR/plugins/$PLUGIN_NAME"
    fi
}


function zsh_add_theme() {
    THEME_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$ZDOTDIR/themes/$THEME_NAME" ]; then 
        # For plugins
	echo "${THEME_NAME} has been loaded!"
        zsh_add_file "themes/$THEME_NAME/$THEME_NAME.zsh-theme"
    else
        git clone "git@github.com:$1.git" "$ZDOTDIR/themes/$THEME_NAME"
    fi
}

function zsh_add_completion() {
    PLUGIN_NAME=$(echo $1 | cut -d "/" -f 2)
    if [ -d "$ZDOTDIR/plugins/$PLUGIN_NAME" ]; then 
        # For completions
		completion_file_path=$(ls $ZDOTDIR/plugins/$PLUGIN_NAME/_*)
		fpath+="$(dirname "${completion_file_path}")"
        zsh_add_file "plugins/$PLUGIN_NAME/$PLUGIN_NAME.plugin.zsh"
    else
        git clone "https://github.com/$1.git" "$ZDOTDIR/plugins/$PLUGIN_NAME"
		fpath+=$(ls $ZDOTDIR/plugins/$PLUGIN_NAME/_*)
        [ -f $ZDOTDIR/.zccompdump ] && $ZDOTDIR/.zccompdump
    fi
	completion_file="$(basename "${completion_file_path}")"
	if [ "$2" = true ] && compinit "${completion_file:1}"
}

function mach_java_mode() {
    #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
    export SDKMAN_DIR="$HOME/.sdkman"
    [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
}

